version: '3.8'
services:
  server:
    build: .
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: myprofile
      MYSQL_USER: son
      MYSQL_PASSWORD: 290602
      MYSQL_ROOT_PASSWORD: 290602

